version: '2'
services:

  web:
    build: ./
    environment:
      - TCP_PORTS=8080
      - BALANCE=source
    links:
      - redis
      - mongo

  redis:
    image: redis:latest

  mongo:
    image: mongo:latest

  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 81:8080
